GCP_PROJECT_ID: 'bdc-trainings'
GOOGLE_CLOUD_PROJECT: 'bdc-trainings'
GCP_LOCATION: 'us-central1'
MOCK_LLM: 'false'
MOCK_TRENDS: 'false'
VECTOR_DB_PROVIDER: 'pinecone'
EMBEDDING_DIMENSION: '768'
VERTEX_GEMINI_MODEL: 'gemini-2.5-flash'
VERTEX_EMBEDDING_MODEL: 'text-embedding-005'
PINECONE_API_KEY: 'pcsk_6omBrB_GZQPt89uUZ2MnDG4Bq3yJf7PzJxT1Eqdzx6WaRQ49Nz3ayN7e5KEJKHAhUsWoXq'
PINECONE_INDEX_NAME: 'retail-layout-rag'
PINECONE_ENVIRONMENT: 'us-east-1'
LANGFUSE_PUBLIC_KEY: 'pk-lf-78e93617-bc90-47cb-96aa-73e7c376210e'
LANGFUSE_SECRET_KEY: 'sk-lf-f14fcd3f-81f2-43bd-a342-09598059d2b4'
LANGFUSE_HOST: 'https://cloud.langfuse.com'
